name: Build & Analyze with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupère ton code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # IMPORTANT pour SonarCloud, permet d'analyser correctement le code

      # Configure Java 25
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      # Cache Maven (accélère le build)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # Lancer les tests (Jacoco génère coverage)
      - name: Run tests
        run: mvn -B test

      # Analyse SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=G0G0R_Java_training
            -Dsonar.organization=g0g0r
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.coveragePlugin=jacoco
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
